# Generated by Django 3.2.3 on 2021-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male')], default=1),
            preserve_default=False,
        ),
    ]
