# Generated by Django 3.2.3 on 2021-05-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_name_who_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question'),
        ),
    ]
